### ISSUE TITLE
Homebridge, 突然エラーで動かなくなった

### ISSUE THREAD

**Issue by mame-n** [mame-n/tank#14]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:557:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:10)

**Comment by mame-n** [comment]
WebiopiでPythonスクリプトを書き、Webiopiを再起動したくらい。
上記エラーは以下にも出ていて、以前はうちでも出ていた。その時にやったことを繰り返してみる。

**Comment by mame-n** [comment]
やったことはapt-get
% sudo apt-get update
% sudo apt-get upgrade

ただその後、
% sudo webiopi -c /etc/webiopi/config -d &
をやったらうまくいったので、init-dで動いている環境がconfigをよまない、デフォルトの可能性が大きい。
というのもMBPから
https://raspi-02.local:8000
で出てくるGPIOピンGUIからはうまくいったので。
自動起動を見直してみる。
